// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaY3NuxxxNiTu8yYX1Bkc7w-N2NuUC-_4',
    appId: '1:964618141857:web:1a3d98a07ec245a924b0e0',
    messagingSenderId: '964618141857',
    projectId: 'forlesson-74a42',
    authDomain: 'forlesson-74a42.firebaseapp.com',
    storageBucket: 'forlesson-74a42.appspot.com',
    measurementId: 'G-LMB9Q6YFM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijl3jGwnd_g-Un3esKYE0KAVrTN2pq8c',
    appId: '1:964618141857:android:133abb782b8a8c5b24b0e0',
    messagingSenderId: '964618141857',
    projectId: 'forlesson-74a42',
    storageBucket: 'forlesson-74a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YpOpYPn5FN1_3KvUUr7LcCz8hw4MDY8',
    appId: '1:964618141857:ios:55c1ed1337ec1e9124b0e0',
    messagingSenderId: '964618141857',
    projectId: 'forlesson-74a42',
    storageBucket: 'forlesson-74a42.appspot.com',
    iosClientId: '964618141857-ofduc32s25lccri2eejg15spog917ime.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthP1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8YpOpYPn5FN1_3KvUUr7LcCz8hw4MDY8',
    appId: '1:964618141857:ios:a862e574acbd79e224b0e0',
    messagingSenderId: '964618141857',
    projectId: 'forlesson-74a42',
    storageBucket: 'forlesson-74a42.appspot.com',
    iosClientId: '964618141857-759elt4kfikv5gu5jbi1nt8g7qe778au.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthP1.RunnerTests',
  );
}
